# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install Checkov
RUN pip install checkov

# Command to run when the container launches
CMD ["checkov", "-d", "/terraform"]
